/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void testRollLength() {
        Library classUnderTest = new Library();
        int inputVal = 8;
        int[] expectedOutput = classUnderTest.roll(inputVal);

        System.out.println(Arrays.toString(expectedOutput));

        assertEquals(expectedOutput.length, 8);
    }

    @Test
    public void testRollContents() {
        Library classUnderTest = new Library();
        int inputVal = 8;
        int[] expectedOutput = classUnderTest.roll(inputVal);

        // how do I test if the values in expectedOutput are <= 6?
        // I would loop through it and then assert what?
    }

    @Test
    public void testContainsDuplicates() {
        Library classUnderTest = new Library();
        int[] inputArray = {1, 2, 3, 3, 5};
        boolean result = classUnderTest.containsDuplicates(inputArray);

        System.out.println(result);

        assertTrue("expected true result", result);
    }

    @Test
    public void testAvg() {
        Library classUnderTest = new Library();
        int[] inputArray = {1, 2, 3};
        double expectedOutput = 2;

        double result = classUnderTest.calculateAverage(inputArray);

        System.out.println(result);

        assertEquals(expectedOutput, result, 0);
    }

    @Test
    public void testArrayWithLowestAvg() {
        Library classUnderTest = new Library();
        int[][] inputArray = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int[] expectedOutput = {55, 54, 60, 53, 59, 57, 61};

        assertArrayEquals("array with lowest avg",
                expectedOutput,
                classUnderTest.arrayWithLowestAvg(inputArray));
    }
}
