/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void testRollLength() {
        Library classUnderTest = new Library();
        int inputVal = 8;
        int[] expectedOutput = classUnderTest.roll(inputVal);

        System.out.println(Arrays.toString(expectedOutput));

        assertEquals(expectedOutput.length, 8);
    }

    @Test
    public void testRollContents() {
        Library classUnderTest = new Library();
        int inputVal = 8;
        int[] expectedOutput = classUnderTest.roll(inputVal);

        // how do I test if the values in expectedOutput are <= 6?
        // I would loop through it and then assert what?
    }

    @Test
    public void testContainsDuplicates() {
        Library classUnderTest = new Library();
        int[] inputArray = {1, 2, 3, 3, 5};
        boolean result = classUnderTest.containsDuplicates(inputArray);

        System.out.println(result);

        assertTrue("expected true result", result);
    }
}
