/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import java.util.Arrays;

public class Library {
    public static int[] roll(int rolls) {
        int[] result = new int[rolls];

        for (int i = 0; i < rolls; i++) {
            result[i] = (int) Math.ceil(Math.random() * 6);
        }
        return result;
    }

    public static boolean containsDuplicates(int[] inputArray) {
        Arrays.sort(inputArray);
        for (int i = 1; i < inputArray.length; i++) {
            if (inputArray[i - 1] == inputArray[i]) {
                return true;
            }
        }
        return false;
    }
}
