/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

public class Library {
    public static int[] roll(int rolls) {
        int[] result = new int[rolls];

        for (int i = 0; i < rolls; i++) {
            result[i] = (int) Math.ceil(Math.random() * 6);
        }
        return result;
    }
}
